apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - network-policy.yaml
  - deployment.yaml
  - service.yaml
  - persistent-volume-claim.yaml
  - external-secret.yaml
  - telemetry-config.yaml
  - telemetry-external-secret.yaml
  - telemetry-delivery-cronjob.yaml
  - telemetry-nightly-cronjob.yaml
